### ISSUE TITLE
Question: comparison with NTL

### ISSUE THREAD

**Issue by alxiong** [keeganryan/flatter#12]
Thanks for open-sourcing the excellent library.

May I ask how `flatter` compares with [`NTL` ](https://libntl.org/) in terms of scope and performance benchmark of comparable algorithms?

**Comment by keeganryan** [comment]
Thanks for your interest. I didn't benchmark the two directly, but I estimate the performance improvements will be comparable to flatter vs fplll. NTL might be faster for very small lattices (maybe of dimension <50 and entries of <500 bits), but flatter will be asymptotically and practically faster for medium to large lattices.

**Comment by alxiong** [comment]
amazing! thanks for replying and will read the crypto23 paper to understand better.

btw, any plan to integrate into `fplll` API and eventually to `fpylll`, or currently the authors prefer to keep it separate for now?

**Comment by alxiong** [comment]
> any plan to integrate into fplll API and eventually to fpylll

nvm my previous question, using it in python is pretty easy: 

```python
import tempfile
from fpylll import IntegerMatrix, LLL
import subprocess


def flatter_reduction(A: IntegerMatrix) -> IntegerMatrix:
    """
    A drop-in replacement for LLL reduction, with Flatter algorithm [crypto23]
    """
    B = None
    with tempfile.NamedTemporaryFile(mode="w") as original, tempfile.NamedTemporaryFile(
        mode="w"
    ) as reduced:
        original.write(f"[\n{A}\n]")
        original.flush()

        code = subprocess.call(["flatter", original.name, reduced.name])
        if code != 0:
            raise Exception("flatter failed to reduce!")
        reduced.flush()  # avoiding extremely rare hardware race condition

        B = IntegerMatrix.from_file(reduced.name)
    return B


A = IntegerMatrix.random(10, "qary", k=5, bits=20)
B = flatter_reduction(A)
C = LLL.reduction(A)
print(f"original:\n{A}")
print(f"flatter reduced:\n{B}")
print(f"LLL reduced:\n{C}")
```
